version: '3.8'

services:
  php:
    build: 
      context: .
      dockerfile: dockerfile
    image: emergency_waitlist:latest
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=em_wait_ash_tom
      - DB_USER=postgres
  
  db:
    image: postgres:14.2
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: always
    environment:
      - POSTGRES_DB=em_wait_ash_tom
      - PGUSER=postgres
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 10
    expose:
      - 5432

volumes:
  db-data: